wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: []
    rows: []
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "gray"
          odd: "white"
      enabled: true
      locations:
        London: "Europe/London"
        California: "America/Los_Angeles"
        Tokyo: "Asia/Tokyo"
        UTC: "Etc/UTC"
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 15
      sort: "chronological"
    gcal:
      colors:
        title: "red"
        description: "lightblue"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      conflictIcon: "🛑"
      currentIcon: "❇️"
      displayResponseStatus: true
      email: "ben@bbrks.me"
      enabled: true
      eventCount: 12
      position:
        top: 2
        left: 0
        height: 2
        width: 2
      refreshInterval: 1
      secretFile: "~/.wtf/gcal/client_secret.json"
      withLocation: true
    prettyweather:
      enabled: true
      city: "crewe"
      position:
        top: 1
        left: 0
        height: 1
        width: 2
      refreshInterval: 300
      unit: "c"
    security:
      enabled: true
      position:
        top: 5
        left: 0
        height: 1
        width: 2
      refreshInterval: 3600
    ipinfo:
      enabled: true
      position:
        top: 4
        left: 0
        height: 1
        width: 2
      refreshInterval: 15
    power:
      enabled: true
      position:
        top: 4
        left: 2
        height: 2
        width: 2
      refreshInterval: 15
    git:
      commitCount: 5
      enabled: true
      position:
        top: 2
        left: 2
        height: 2
        width: 4
      refreshInterval: 8
      repositories:
      - "/Users/bbrks/.dotfiles"
      - "/Users/bbrks/dev/bbrks.me"
    github:
      enabled: true
      position:
        top: 0
        left: 2
        height: 2
        width: 4
      refreshInterval: 300
      repositories:
        bbrks.me: "bbrks"
        sync_gateway: "couchbase"
        sync-gateway-accel: "couchbaselabs"
      username: "bbrks"
    # jira:
    #   colors:
    #     rows:
    #       even: "lightblue"
    #       odd: "white"
    #   domain: "https://jira.home.bbrks.me"
    #   email: "ben@bbrks.me"
    #   enabled: true
    #   jql: ""
    #   position:
    #     top: 2
    #     left: 2
    #     height: 2
    #     width: 4
    #   project: "HOUSE"
    #   refreshInterval: 900
    #   username: "bbrks"
    todo:
      checkedIcon: "✔"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 4
        left: 4
        height: 2
        width: 2
      refreshInterval: 3600
